###########################################
# ODROID-C2 的 U-Boot 启动脚本

# 获取环境分区的起始位置
setenv devnum 1
part start mmc ${devnum} 6 mmc_env
mmc dev ${devnum}

# 定义加载启动状态的命令
setenv loadbootstate " \
    echo 'loading env...'; \
    mmc read ${ramdisk_addr_r} ${mmc_env} 0x40; \
    env import -c ${ramdisk_addr_r} 0x8000;"

# 定义存储启动状态的命令
setenv storebootstate " \
    echo 'storing env...'; \
    env export -c -s 0x8000 ${ramdisk_addr_r} BOOT_ORDER BOOT_A_LEFT BOOT_B_LEFT MACHINE_ID; \
    mmc write ${ramdisk_addr_r} ${mmc_env} 0x40;"

# 加载启动状态并设置默认值
run loadbootstate
# 设置默认启动顺序为 A B
test -n "${BOOT_ORDER}" || setenv BOOT_ORDER "A B"
# 设置分区 A/B 的剩余启动次数
test -n "${BOOT_A_LEFT}" || setenv BOOT_A_LEFT 3
test -n "${BOOT_B_LEFT}" || setenv BOOT_B_LEFT 3

# 首次启动条件检查
test -n "${MACHINE_ID}" || setenv BOOT_CONDITION "systemd.condition-first-boot=true"

# Home Assistant OS 的基本启动参数
setenv bootargs_hassos "zram.enabled=1 zram.num_devices=3 systemd.machine_id=${MACHINE_ID} fsck.repair=yes ${BOOT_CONDITION}"

# 设置 A/B 分区的根文件系统启动参数
setenv bootargs_a "root=PARTUUID=8d3d53e3-6d49-4c38-8349-aff6859e82fd ro rootwait"
setenv bootargs_b "root=PARTUUID=a3ec664e-32ce-4665-95ea-7ae90ce9aa20 ro rootwait"

# 加载自定义配置文件 haos-config.txt
if test -e mmc ${devnum}:1 haos-config.txt; then
  fatload mmc ${devnum}:1 ${ramdisk_addr_r} haos-config.txt
  env import -t ${ramdisk_addr_r} ${filesize}
fi

# 加载额外的启动参数
# fileenv mmc ${devnum}:1 ${ramdisk_addr_r} cmdline.txt cmdline

# 加载设备树文件
setenv fdtfile "rk3328-nanopi-r2s.dtb"
echo "Loading standard device tree ${fdtfile}"
fatload mmc ${devnum}:1 ${fdt_addr_r} ${fdtfile}
fdt addr ${fdt_addr_r}

# 加载设备树覆盖文件
# fdt resize 65536
# for overlay_file in ${overlays}; do
#   if fatload mmc ${devnum}:1 ${ramdisk_addr_r} overlays/${overlay_file}.dtbo; then
#     echo "Applying kernel provided DT overlay ${overlay_file}.dtbo"
#     fdt apply ${ramdisk_addr_r} || setenv overlay_error "true"
#   fi
# done
# if test "${overlay_error}" = "true"; then
#   echo "Error applying DT overlays, restoring original DT"
#   fatload mmc ${devnum}:1 ${fdt_addr_r} ${fdtfile}
# fi

# 分区说明:
# 1. boot
# 2. Extended partition
# 3. Overlay
# 4. Data
# 5. KernelA
# 6. SystemA
# 7. KernelB
# 8. SystemB
# 9. BootInfo

# A/B 系统启动逻辑
setenv bootargs
for BOOT_SLOT in "${BOOT_ORDER}"; do
  if test "x${bootargs}" != "x"; then
    # skip remaining slots
  elif test "x${BOOT_SLOT}" = "xA"; then
    if test ${BOOT_A_LEFT} -gt 0; then
      setexpr BOOT_A_LEFT ${BOOT_A_LEFT} - 1
      echo "Trying to boot slot A, ${BOOT_A_LEFT} attempts remaining. Loading kernel ..."
      if load ${devtype} ${devnum}:2 ${kernel_addr_r} Image; then
          setenv bootargs "${bootargs_hassos} ${bootargs_a} rauc.slot=A ${cmdline}"
      fi
    fi
  elif test "x${BOOT_SLOT}" = "xB"; then
    if test ${BOOT_B_LEFT} -gt 0; then
      setexpr BOOT_B_LEFT ${BOOT_B_LEFT} - 1
      echo "Trying to boot slot B, ${BOOT_B_LEFT} attempts remaining. Loading kernel ..."
      if load ${devtype} ${devnum}:4 ${kernel_addr_r} Image; then
          setenv bootargs "${bootargs_hassos} ${bootargs_b} rauc.slot=B ${cmdline}"
      fi
    fi
  fi
done

# 启动状态处理
if test -n "${bootargs}"; then
  run storebootstate
else
  echo "No valid slot found, resetting tries to 3"
  setenv BOOT_A_LEFT 3
  setenv BOOT_B_LEFT 3
  run storebootstate
  reset
fi

# 显示最终的启动参数并启动内核
printenv bootargs
echo "Starting kernel"
booti ${kernel_addr_r} - ${fdt_addr_r}

echo "Boot failed, resetting..."
reset
